# Generated by Django 2.2.8 on 2020-08-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description hiahfvr  hdfisndc hiefwhidc hfewih hi'),
            preserve_default=False,
        ),
    ]
